/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")

    repositories {
        // Use the plugin portal to apply community plugins in convention plugins.
        gradlePluginPortal()
        mavenCentral()
        maven("https://maven.fabricmc.net/")
        maven("https://maven.shedaniel.me/")
        maven("https://maven.neoforged.net/releases")
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "Orbis"
include("common", "games:minecraft",
    "migrators:rpgregions", "migrators:worldguard",
    "platforms:paper", "api:paper-api",
    "platforms:sponge", "api:sponge-api",
//    "platforms:modded:modded-common",
    //"platforms:modded:fabric", "api:fabric-api",
//    "platforms:modded:neoforge", "api:neoforge-api"
)

val hytaleServerJarFile: String by settings
val hytaleServerJar = rootDir.resolve(hytaleServerJarFile.trim())
if (hytaleServerJar.exists()) {
    include("games:hytale", "platforms:hytale", "api:hytale-api")
    logger.lifecycle("Hytale server jar found at ${hytaleServerJar.relativeTo(rootDir)} - we will build against the Hytale game.")
} else {
    logger.warn("Skipping building against Hytale game because ${hytaleServerJar.relativeTo(rootDir)} is missing")
}
