/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
    mavenCentral()
    maven("https://maven.fabricmc.net/")
}

dependencies {
    implementation("com.gradleup.shadow:shadow-gradle-plugin:9.0.0-beta17")
    implementation("com.diffplug.spotless:spotless-plugin-gradle:7.0.2")
    implementation("net.kyori:indra-licenser-spotless:3.1.3")
    implementation("net.kyori:blossom:2.1.0")
}
