/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.java-library-conventions")
    `maven-publish`
}

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "org.empirewar.orbis"
            artifactId = project.name
            version = project.version.toString()
            from(components["java"])
        }
    }

    repositories {
        // See Gradle docs for how to provide credentials to PasswordCredentials
        // https://docs.gradle.org/current/samples/sample_publishing_credentials.html
        maven {
            val snapshotUrl = "https://repo.convallyria.com/snapshots/"
            val releaseUrl = "https://repo.convallyria.com/releases/"

            // Check which URL should be used
            url = if (project.version.toString().endsWith("SNAPSHOT")) {
                uri(snapshotUrl)
            } else {
                uri(releaseUrl)
            }

            name = "snapshots"
            url = uri("https://repo.convallyria.com/snapshots/")
            credentials {
                username = System.getenv("MAVEN_USERNAME")
                password = System.getenv("MAVEN_PASSWORD")
            }
        }
    }
}