name: Publish Orbis Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # Handles Gradle wrapper validation and basic caching

      - name: Build all variants
        run: ./gradlew build

      - name: Collect release jars (exclude -dev, -sources, -javadoc, -shadow)
        run: |
          shopt -s globstar
          mkdir release-jars
          for f in platforms/**/build/libs/*.jar; do
            case "$f" in
              *-dev.jar|*-dev-shadow.jar|*-sources.jar|*-javadoc.jar) ;; # skip
              *) cp "$f" release-jars/ ;;
            esac
          done
          ls -lh release-jars

      - name: Publish Orbis for Paper
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.RELEASES_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: O785bSfs
          files: release-jars/orbis-paper-*.jar
          game-versions: |
            >=1.21.4
          loaders: |
            paper
            purpur
          version-type: release

      - name: Publish Orbis for Sponge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.RELEASES_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: O785bSfs
          files: release-jars/orbis-sponge-*.jar
          game-versions: |
            >=1.21.4
          loaders: sponge
          version-type: release

      - name: Publish Orbis for Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.RELEASES_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: O785bSfs
          files: release-jars/orbis-fabric-*.jar
          loaders: fabric
          version-type: release

      - name: Publish Orbis for NeoForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.RELEASES_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: O785bSfs
          files: release-jars/orbis-neoforge-*.jar
          loaders: neoforge
          version-type: release
