name: Publish Orbis Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # Handles Gradle wrapper validation and basic caching

      - name: Build all variants
        run: ./gradlew build

      - name: Publish Orbis for Paper
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.RELEASES_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: O785bSfs
          files: |
            platforms/paper/build/libs/orbis-paper-!(*-dev|-sources|-javadoc).jar
          game-versions: |
            >=1.21.4
          version-type: release

      - name: Publish Orbis for Sponge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.RELEASES_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: O785bSfs
          files: |
            platforms/sponge/build/libs/orbis-sponge-!(*-dev|-sources|-javadoc).jar
          game-versions: |
            >=1.21.4
          version-type: release

      - name: Publish Orbis for Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.RELEASES_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: O785bSfs
          files: |
            platforms/modded/fabric/build/libs/orbis-fabric-!(*-dev|-sources|-javadoc).jar
          version-type: release

      - name: Publish Orbis for NeoForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.RELEASES_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: O785bSfs
          files: |
            platforms/modded/neoforge/build/libs/orbis-neoforge-!(*-dev|-sources|-javadoc).jar
          version-type: release
